export default {
  USER_CONNECTED: 'USER_CONNECTED',
  NEW_MESSAGE: 'NEW_MESSAGE',
  CHANGE_USERNAME: 'CHANGE_USERNAME',
  GAME_START: 'GAME_START',
  CREATE_GAME_ROOM: 'CREATE_GAME_ROOM',
  NEW_GAME_ROOM_CREATED: 'NEW_GAME_ROOM_CREATED',
  ENTER_TO_GAME_ROOM: 'ENTER_TO_GAME_ROOM',
  OPPONENT_ENTRANCE_TO_GAME_ROOM: 'OPPONENT_ENTRANCE_TO_GAME_ROOM',
  SELECT_GESTURE: 'SELECT_GESTURE'
};
